### ISSUE TITLE
Frontend: Create LogIn Component

### ISSUE THREAD

**Issue by starvader13** [starvader13/Patra#35]
**Task:**  
Enhance the LogIn component with specified fields and improve its design.

**Requirements:**
- **Fields:**
  - `email`
  - `password`
- **Design:**
  - Responsive layout
  - Visually appealing interface
  - Error Message

**Action Items:**
- [x] Add the `username`, `email`, and `password` fields to the LogIn component.
- [x] Improve the visual appeal of the signup form.
- [x] Added error message for the input field.
